# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11c44d03a9b1dcf8a6825f980716fb3ed88885a3a0337bb527e35a512480e4d00eb5774b732997209ae1106da43322124ba8df8adfc72df366f0200c9c31adf3

test:
  secret_key_base: 9597c7ce04de467f6112d4b656d65ff8b48f268288901a13ccad0231c69322e95200d66fe15c7c9552f8a35fda3362dff63f2a0c33d2239a45f5dc6b4f9b523a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
